FROM node:22-alpine
WORKDIR /usr/src/app
RUN apk add --no-cache openssl
COPY ./dist/apps/rahat/ ./
RUN npm install --legacy-peer-deps
RUN npm install -g pnpm@9.15.2 && pnpm prisma generate
CMD ["node", "main.js"]
