# Install dependencies only when needed
FROM node:18-alpine3.17 AS deps
WORKDIR /usr/src/app
COPY ./dist/apps/beneficiary/package.json .npmrc ./
RUN npm install -g pnpm && pnpm install

FROM node:18-alpine3.17 AS builder
WORKDIR /usr/src/app
COPY ./dist/apps/beneficiary/ ./
COPY --from=deps /usr/src/app/node_modules ./node_modules
RUN npx prisma generate
CMD [ "node", "main.js" ]