FROM node:20-alpine3.19 AS deps
WORKDIR /usr/src/app
COPY ./dist/apps/beneficiary/package.json ./
RUN apk add --no-cache openssl && \
    npm install -g pnpm@9.15.2 && \
    pnpm install --no-frozen-lockfile

FROM node:20-alpine3.19 AS runner
WORKDIR /usr/src/app
RUN apk add --no-cache openssl
COPY ./dist/apps/beneficiary/ ./
COPY --from=deps /usr/src/app/node_modules ./node_modules
RUN npm install -g pnpm@9.15.2 && pnpm prisma generate
CMD ["node", "main.js"]
