volumes:
  rahat_pg_data:
    external: true
  rahat_pg_admin_data:
    external: true
  rahat_ganache_data:
    external: true
  rahat_redis_data:
    external: true

services:
  postgres-rahat:
    image: postgres:14
    restart: always
    container_name: postgres-rahat
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    command: postgres -c max_prepared_transactions=100
    volumes:
      - rahat_pg_data:/var/lib/postgresql/data
    ports:
      - '${PG_PORT}:5432'
    networks:
      - rahat_platform

  pgadmin-rahat:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: pgadmin-rahat
    volumes:
      - rahat_pg_admin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    ports:
      - '${PGADMIN_PORT}:80'
    depends_on:
      - postgres-rahat
    networks:
      - rahat_platform

  ganache-rahat:
    image: trufflesuite/ganache
    platform: linux/amd64
    container_name: ganache-rahat
    command: --accounts 20 -m "${MNEMONIC}" --wallet.accountKeysPath /db/accounts --database.dbPath "/db" --logging.file /db/ganache.log --miner.blockTime 2 --chain.networkId "${GANACHE_PORT}" --chain.chainId "${GANACHE_PORT}" --chain.asyncRequestProcessing true
    restart: always
    ports:
      - '${GANACHE_PORT}:8545'
    volumes:
      - rahat_ganache_data:/db
    networks:
      - rahat_platform

  redis-rahat:
    container_name: redis-rahat
    image: bitnami/redis:latest
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
    volumes:
      - rahat_redis_data:/data
    networks:
      - rahat_platform
      - rahat_projects

  bull-board:
    image: deadly0/bull-board:latest
    restart: always
    container_name: bull-board
    ports:
      - '5689:3000'
    environment:
      - REDIS_HOST=redis-rahat # Changed from localhost to the service name
      - REDIS_PORT=6379 # Ensure REDIS_PORT is set to 6379 in your environment file
      - REDIS_PASSWORD=${REDIS_PASS}
    depends_on:
      - redis-rahat
    networks:
      - rahat_platform

networks:
  rahat_platform:
    external: true
  rahat_projects:
    external: true
