export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  UKNOWN = 'UNKNOWN',
}

export enum BankedStatus {
  UNKNOWN = 'UNKNOWN',
  UNBANKED = 'UNBANKED',
  BANKED = 'BANKED',
  UNDER_BANKED = 'UNDER_BANKED',
}

export enum InternetStatus {
  UNKNOWN = 'UNKNOWN',
  NO_INTERNET = 'NO_INTERNET',
  HOME_INTERNET = 'HOME_INTERNET',
  MOBILE_INTERNET = 'MOBILE_INTERNET',
}

export enum PhoneStatus {
  UNKNOWN = 'UNKNOWN',
  NO_PHONE = 'NO_PHONE',
  FEATURE_PHONE = 'FEATURE_PHONE',
  SMART_PHONE = 'SMART_PHONE',
}
