name: EL Release CI/CD
on:
  workflow_dispatch:

env:
  CI: false

jobs:
 rahat-platform:
    name: rahat-platform
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'release/') && github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: Install pnpm
        run: |
          npm install -g pnpm@8.14.1
          pnpm install
          npx nx reset
          pnpm prisma:generate
          pnpm build:all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from package.json
        id: extract_version
        run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Extract Timestamp
        id: extract-timestamp
        run: |
          TIMESTAMP=$(date "+%Y-%m-%d_%H-%M-%S")
          echo "timestamp=$TIMESTAMP" >> $GITHUB_ENV

      # Beneficiary Image
      - name: build && push beneficiary
        id: build-push-beneficiary
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.beneficiary
          push: ${{ github.event_name == 'workflow_dispatch' }}
          tags: |
            esatya/rahat-platform-beneficiary:el-release
            esatya/rahat-platform-beneficiary:el-release-${{ env.VERSION }}
            esatya/rahat-platform-beneficiary:el-release-${{ env.VERSION }}-${{ env.timestamp }}

      # Rahat Image
      - name: build && push rahat
        id: build-push-rahat
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.rahat
          push: ${{ github.event_name == 'workflow_dispatch' }}
          tags: |
            esatya/rahat-platform-rahat:el-release
            esatya/rahat-platform-rahat:el-release-${{ env.VERSION }}
            esatya/rahat-platform-rahat:el-release-${{ env.VERSION }}-${{ env.timestamp }}