name: Test Coverage CI/CD
on:
  push:
    branches:
      - 'benef-test'
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'benef-test'
      - 'main'
      - 'dev'
  workflow_dispatch:

env:
  CI: false
  env_npmrc: ${{ secrets.ENV_NPMRC }}

jobs:
  test-coverage:
    name: Run tests and upload coverage to Coveralls
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: import env file
      #   run: |
      #     touch ./.npmrc && echo "$env_npmrc" >> ./.npmrc

      - uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: install dependencies and Bootstrap apps
        run: |
          npm install -g pnpm@8.14.1
          pnpm install
          pnpm bootstrap
          pnpm rahat&
          pnpm beneficiary&
          sleep 5

      - name: Run Test Coverage
        run: pnpm test:coverage -- --coverageReporters=lcov text

      - name: Upload rahat app coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: rahat
          file: coverage/apps/rahat/lcov.info
          parallel: true

      - name: Upload beneficiary app coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: beneficiary
          file: coverage/apps/beneficiary/lcov.info
          parallel: true

      - name: Upload sdk coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: sdk
          file: coverage/libs/sdk/lcov.info
          parallel: true

      - name: Finalize Coveralls parallel build
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
